Fixed Rake task double runner call
Discovered when being used from within the Gemsmith project upon
upgrading to 12.0.0. The double call was causing the following
error to show up:

    NoMethodError:
      undefined method `call' for []:Array

This was typo on my part as the runner only needs to be called once.